/**
 * Discrepancia
 * Corresponde al módulo de discrepancia-Crear Discrepancia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Schema for error response body
 */
export interface ApiMessage { 
    /**
     * Codigo de respuesta. 
     */
    code: string;
    /**
     * Texto del mensaje. 
     */
    message: string;
}