/**
 * Discrepancia
 * Corresponde al módulo de discrepancia-Crear Discrepancia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Atributo numerico que establece el codigo de identificación del recurso. 
 */
export type CodeGeneral = string;